id: /subscriptions/443c2eca-50c0-422f-b3c5-866b6a3d7d93/resourceGroups/rg-iris-symphony-osha5/providers/Microsoft.App/containerapps/ca-svo-convo-2ygsjtole3k4o
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? /subscriptions/443c2eca-50c0-422f-b3c5-866b6a3d7d93/resourcegroups/rg-iris-symphony-osha5/providers/Microsoft.ManagedIdentity/userAssignedIdentities/id-2ygsjtole3k4o
    : clientId: d40daa90-0700-4c7c-b111-cf21b5ec7aaf
      principalId: c207022d-0bb8-4088-93a2-845f4a03613f
location: West US 3
name: ca-svo-convo-2ygsjtole3k4o
properties:
  configuration:
    activeRevisionsMode: Single
    dapr: null
    identitySettings: []
    ingress:
      additionalPortMappings: null
      allowInsecure: false
      clientCertificateMode: null
      corsPolicy: null
      customDomains: null
      exposedPort: 0
      external: true
      fqdn: ca-svo-convo-2ygsjtole3k4o.greenbeach-ffc375dd.westus3.azurecontainerapps.io
      ipSecurityRestrictions: null
      stickySessions: null
      targetPort: 80
      traffic:
      - latestRevision: true
        weight: 100
      transport: Http
    maxInactiveRevisions: null
    registries:
    - identity: ''
      passwordSecretRef: ca08c54e3510acrazurecrio-ca08c54e3510acr
      server: ca08c54e3510acr.azurecr.io
      username: ca08c54e3510acr
    runtime: null
    secrets:
    - name: storage-connection-string
    - name: ca08c54e3510acrazurecrio-ca08c54e3510acr
    service: null
  customDomainVerificationId: 0E75637962A1BCA01010B9CC843B1707C135D02A7CD212B3439CAC903DB08F8C
  delegatedIdentities: []
  environmentId: /subscriptions/443c2eca-50c0-422f-b3c5-866b6a3d7d93/resourceGroups/rg-iris-symphony-osha5/providers/Microsoft.App/managedEnvironments/cae-iris-2ygsjtole3k4o
  eventStreamEndpoint: https://westus3.azurecontainerapps.dev/subscriptions/443c2eca-50c0-422f-b3c5-866b6a3d7d93/resourceGroups/rg-iris-symphony-osha5/containerApps/ca-svo-convo-2ygsjtole3k4o/eventstream
  latestReadyRevisionName: ca-svo-convo-2ygsjtole3k4o--0000003
  latestRevisionFqdn: ca-svo-convo-2ygsjtole3k4o--0000003.greenbeach-ffc375dd.westus3.azurecontainerapps.io
  latestRevisionName: ca-svo-convo-2ygsjtole3k4o--0000003
  managedEnvironmentId: /subscriptions/443c2eca-50c0-422f-b3c5-866b6a3d7d93/resourceGroups/rg-iris-symphony-osha5/providers/Microsoft.App/managedEnvironments/cae-iris-2ygsjtole3k4o
  outboundIpAddresses:
  - 4.249.94.249
  provisioningState: Succeeded
  runningStatus: Running
  template:
    containers:
    - env:
      - name: AGENTS_PROJECT_ENDPOINT
        value: https://aif-2ygsjtole3k4o.services.ai.azure.com/api/projects/aif-2ygsjtole3k4o-agents
      - name: DELETE_OLD_AGENTS
        value: 'false'
      - name: MAX_AGENT_RETRY
        value: '5'
      - name: USE_MI_AUTH
        value: 'true'
      - name: MI_CLIENT_ID
        value: d40daa90-0700-4c7c-b111-cf21b5ec7aaf
      - name: AOAI_ENDPOINT
        value: https://aif-2ygsjtole3k4o.openai.azure.com/
      - name: AOAI_DEPLOYMENT
        value: gpt-4o
      - name: TRANSLATOR_RESOURCE_ID
        value: /subscriptions/443c2eca-50c0-422f-b3c5-866b6a3d7d93/resourceGroups/rg-iris-symphony-osha5/providers/Microsoft.CognitiveServices/accounts/aif-2ygsjtole3k4o
      - name: TRANSLATOR_REGION
        value: westus3
      - name: SEARCH_ENDPOINT
        value: https://srch-2ygsjtole3k4o.search.windows.net
      - name: SEARCH_INDEX_NAME
        value: sagevia-osha-knowledge-idx
      - name: EMBEDDING_DEPLOYMENT_NAME
        value: text-embedding-3-large
      - name: EMBEDDING_MODEL_NAME
        value: text-embedding-3-large
      - name: EMBEDDING_MODEL_DIMENSIONS
        value: '3072'
      - name: STORAGE_ACCOUNT_NAME
        value: st2ygsjtole3k4o
      - name: STORAGE_ACCOUNT_CONNECTION_STRING
        secretRef: storage-connection-string
      - name: BLOB_CONTAINER_NAME
        value: osha-knowledge-files
      - name: LANGUAGE_ENDPOINT
        value: https://aif-2ygsjtole3k4o.cognitiveservices.azure.com/
      - name: CLU_PROJECT_NAME
        value: sagevia-osha-clu
      - name: CLU_MODEL_NAME
        value: clu-m1
      - name: CLU_DEPLOYMENT_NAME
        value: production
      - name: CLU_CONFIDENCE_THRESHOLD
        value: '0.7'
      - name: CQA_PROJECT_NAME
        value: sagevia-osha-cqa
      - name: CQA_DEPLOYMENT_NAME
        value: production
      - name: CQA_CONFIDENCE_THRESHOLD
        value: '0.8'
      - name: ORCHESTRATION_PROJECT_NAME
        value: sagevia-osha-orchestration
      - name: ORCHESTRATION_MODEL_NAME
        value: orch-m1
      - name: ORCHESTRATION_DEPLOYMENT_NAME
        value: production
      - name: ORCHESTRATION_CONFIDENCE_THRESHOLD
        value: '0.7'
      - name: PII_ENABLED
        value: 'true'
      - name: PII_CATEGORIES
        value: person,organization,address,phonenumber
      - name: PII_CONFIDENCE_THRESHOLD
        value: '0.7'
      - name: ROUTER_TYPE
        value: ORCHESTRATION
      - name: APP_MODE
        value: SEMANTIC_KERNEL
      - name: IRIS_ZONE1_ECFR_URL
        value: ''
      - name: IRIS_ZONE1_RECORDABILITY_URL
        value: ''
      - name: IRIS_ZONE1_ANALYTICS_URL
        value: ''
      - name: TRIAGE_AGENT_ID
        value: asst_Xeumpw49JJ2QDxmAdJ36NMhL
      - name: LUMI_AGENT_ID
        value: asst_WqND6bfEODDQMe7DspwqQXxK
      - name: SCIENCES_AGENT_ID
        value: asst_Su02DkXtTzyYt5N0gtKvC0YC
      - name: GOVERNANCE_AGENT_ID
        value: asst_T3pi5nSo4UBT0Vz46pE6jqDy
      - name: ANALYTICS_AGENT_ID
        value: asst_S3NmWxc5N0dQRuFSRtQlRzc6
      - name: EXPERIENCE_AGENT_ID
        value: asst_682AlT7OQyjvamiVwG0uR4yG
      - name: TRANSLATION_AGENT_ID
        value: asst_skeQ8bviyzLJ8RoiatUOOctc
      - name: HEAD_SUPPORT_AGENT_ID
        value: asst_WqND6bfEODDQMe7DspwqQXxK
      - name: IRIS_ZONE2_INCIDENTS_URL
        value: ''
      - name: IRIS_ZONE2_DOCUMENTS_URL
        value: ''
      image: mcr.microsoft.com/azuredocs/containerapps-helloworld:latest
      name: convo-agent
      resources:
        cpu: 0.5
        ephemeralStorage: 2Gi
        memory: 1Gi
    - env:
      - name: LANGUAGE_ENDPOINT
        value: https://aif-2ygsjtole3k4o.cognitiveservices.azure.com/
      image: ca08c54e3510acr.azurecr.io/ca-svo-convo-2ygsjtole3k4o:20260116101121474714
      name: ca-svo-convo-2ygsjtole3k4o
      resources:
        cpu: 0.5
        ephemeralStorage: 2Gi
        memory: 1Gi
    initContainers: null
    revisionSuffix: ''
    scale:
      cooldownPeriod: 300
      maxReplicas: 3
      minReplicas: 0
      pollingInterval: 30
      rules:
      - http:
          metadata:
            concurrentRequests: '10'
        name: http-scaling
    serviceBinds: null
    terminationGracePeriodSeconds: null
    volumes: null
  workloadProfileName: null
resourceGroup: rg-iris-symphony-osha5
systemData:
  createdAt: '2026-01-16T09:12:21.6436591'
  createdBy: Stephanie@sageknoll.co
  createdByType: User
  lastModifiedAt: '2026-01-16T10:34:42.1673249'
  lastModifiedBy: Stephanie@sageknoll.co
  lastModifiedByType: User
type: Microsoft.App/containerApps
